/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;
import Panel.*;
import Model.TimerSpecification;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
 
/**
 *
 * @author peach
 */
public class CreateTimer extends javax.swing.JPanel /*implements ActionListener*/ {
    
    public CreateTimer() {
        initComponents();

        workDuration.setValue(25);
        restDuration.setValue(5);
        workDuration.addChangeListener((ChangeEvent e) -> {
            int val1 = (int) workDuration.getValue();
            if (val1 < 0) {
                workDuration.setValue(0);
                StudySlider.setValue(0);
            } else if (val1 > 120){
                workDuration.setValue(120);
                StudySlider.setValue(120);
            } else {
                StudySlider.setValue(val1);
            }
        });
        
        restDuration.addChangeListener((ChangeEvent e) -> {
            int val2 = (int) restDuration.getValue();
            if (val2 < 0) {
                RestSlider.setValue(0);
            } else if (val2 > 120){
                RestSlider.setValue(120);
            } else {
                RestSlider.setValue(val2);
            }
        });
        
        //setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        StudySlider = new javax.swing.JSlider(0, 120, 25);
        RestSlider = new javax.swing.JSlider(0, 120, 5);
        timerName = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        workDuration = new javax.swing.JSpinner();
        restDuration = new javax.swing.JSpinner();

        jButton1.setText("jButton1");

        setOpaque(false);

        jLabel3.setText("Set Custom Timer");

        jLabel4.setText("Work Duration");

        jLabel5.setText("Rest Duration");

        StudySlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                StudySliderStateChanged(evt);
            }
        });

        RestSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RestSliderStateChanged(evt);
            }
        });

        timerName.setText("Name of Custom Timer");
        timerName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                timerNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                timerNameFocusLost(evt);
            }
        });

        jButton3.setText("Save Settings");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(StudySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RestSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addComponent(jButton3))
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(timerName, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(workDuration, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(restDuration))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(StudySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(workDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(RestSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(restDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(timerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jButton3)))
                .addContainerGap(220, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // update the study duration textfield to reflect the slider
    private void StudySliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_StudySliderStateChanged
        // TODO add your handling code here:
        workDuration.setValue(StudySlider.getValue());
    }//GEN-LAST:event_StudySliderStateChanged
    
    // update the rest duration textfield to reflect the slider
    private void RestSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RestSliderStateChanged
        // TODO add your handling code here:
        restDuration.setValue(RestSlider.getValue());
    }//GEN-LAST:event_RestSliderStateChanged

    // place holder for text field for name of custom timer
    private void timerNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_timerNameFocusGained
        // TODO add your handling code here:
        if (timerName.getText().equals("Name of Custom Timer")) {
                    timerName.setText("");
                }
            
    }//GEN-LAST:event_timerNameFocusGained

    private void timerNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_timerNameFocusLost
        // TODO add your handling code here:
        if (timerName.getText().equals("")) {
            timerName.setText("Name of Custom Timer");
        }
    }//GEN-LAST:event_timerNameFocusLost

    
    //create a timer with the specifications, add into combobox and reset values of slider & text field and rest fexi field
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        TimerSpecification newCustomTimer = new TimerSpecification(timerName.getText(),/* StudySlider.getValue()*/(int) workDuration.getValue(),(int) restDuration.getValue());
        StartTimer.addTimer(newCustomTimer);
        
        TimerSpecification currentlyChosen = (TimerSpecification) StartTimer.jComboBox1.getSelectedItem();
        timerName.setText("Name of Custom Timer");

        StudySlider.setValue(currentlyChosen.studyTime);
        RestSlider.setValue(currentlyChosen.breakTime);
        workDuration.setValue(currentlyChosen.studyTime);
        restDuration.setValue(currentlyChosen.breakTime);
    }//GEN-LAST:event_jButton3ActionPerformed

    
    public static void setSlidersToTimer(TimerSpecification tS) {
        
        StudySlider.setValue(tS.studyTime);
        RestSlider.setValue(tS.breakTime);
        workDuration.setValue(tS.studyTime);
        restDuration.setValue(tS.breakTime);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JSlider RestSlider;
    private static javax.swing.JSlider StudySlider;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private static javax.swing.JSpinner restDuration;
    private javax.swing.JTextField timerName;
    private static javax.swing.JSpinner workDuration;
    // End of variables declaration//GEN-END:variables
}
