/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import Model.Cell;
import Model.MainTask;
import Model.SubTask;
import Model.Today;
import Panel.TasksPanel;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;

/**
 *
 * @author peach
 */
public class DateComponent extends javax.swing.JLayeredPane {

    /**
     * Creates new form DateComponent
     */
    

    
    private int month;
    private int year;
    private HashMap<String, Integer> weightWeekMap; 
    private ArrayList<MainTask> mainTasks;
    
    public DateComponent(int month, int year) {
        initComponents();
        mainTasks = TasksPanel.getMainTasks();
        
        this.month = month;
        this.year = year;
        weightWeekMap = new HashMap<>();
         
        init();
    }

    
    private void init() {
        mon.asTitle();
        tues.asTitle();
        wed.asTitle();
        thurs.asTitle();
        fri.asTitle();
        sat.asTitle();
        sun.asTitle();

        Calendar cal = Calendar.getInstance();
        if (mainTasks != null) {
            for (MainTask mainTask : mainTasks) {
                for (int i = 0; i < mainTask.numOfSubTasks(); i++) {
                    SubTask subTask = mainTask.getSubTask(i);
                    cal.setTime(subTask.deadline);

                    String weekYear = cal.get(Calendar.WEEK_OF_YEAR) + "-" + cal.get(Calendar.YEAR);
                    int weight = subTask.weight;

                    if (weightWeekMap.containsKey(weekYear)) {
                        int currentWeight = weightWeekMap.get(weekYear);
                        weightWeekMap.put(weekYear, currentWeight + weight);
                    } else {
                        weightWeekMap.put(weekYear, weight);
                    }
                }
            }
            setDate();
        }  
    }
    
    private void setDate() {
        Calendar cal = Calendar.getInstance();
        cal.set(Calendar.YEAR, year);
        cal.set(Calendar.MONTH, month - 1); // month jan as 0 so start from 0
        cal.set(Calendar.DATE, 1);
        
        int startDay = cal.get(Calendar.DAY_OF_WEEK) - 1; // get day of week -1 to index
        cal.add(Calendar.DATE, -startDay);
        
        Today today = getToday();
        String weekYear;
        
        for (Component com:getComponents()) {
            Cell cell = (Cell) com;
            if (!cell.isTitle()) {
                cell.setText(cal.get(Calendar.DATE) + "");
                cell.setDate(cal.getTime());
                cell.currentMonth(cal.get(Calendar.MONTH) == month - 1);
                
                if (today.isToday(new Today(cal.get(Calendar.DATE), cal.get(Calendar.MONTH) + 1, cal.get(Calendar.YEAR)))) {
                    cell.setAsToday();
                }
                
                weekYear = cal.get(Calendar.WEEK_OF_YEAR) + "-" + cal.get(Calendar.YEAR);
                
                if (this.weightWeekMap.containsKey(weekYear)) {
                    //System.out.println("key found: " + weekYear + "    weight: " + this.weightWeekMap.get(weekYear));
                    cell.setWeekWeight(this.weightWeekMap.get(weekYear));
                }

                cal.add(Calendar.DATE, 1); // up 1 day
            }
        }
    }
    
    
    
    
    private Today getToday() {
        Calendar cal = Calendar.getInstance();
        cal.setTime(new Date());
        return new Today(cal.get(Calendar.DATE), cal.get(Calendar.MONTH) + 1, cal.get(Calendar.YEAR));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sun = new Model.Cell();
        mon = new Model.Cell();
        tues = new Model.Cell();
        wed = new Model.Cell();
        thurs = new Model.Cell();
        fri = new Model.Cell();
        sat = new Model.Cell();
        cell8 = new Model.Cell();
        cell9 = new Model.Cell();
        cell10 = new Model.Cell();
        cell11 = new Model.Cell();
        cell12 = new Model.Cell();
        cell13 = new Model.Cell();
        cell14 = new Model.Cell();
        cell15 = new Model.Cell();
        cell16 = new Model.Cell();
        cell17 = new Model.Cell();
        cell18 = new Model.Cell();
        cell19 = new Model.Cell();
        cell20 = new Model.Cell();
        cell21 = new Model.Cell();
        cell22 = new Model.Cell();
        cell23 = new Model.Cell();
        cell24 = new Model.Cell();
        cell25 = new Model.Cell();
        cell26 = new Model.Cell();
        cell27 = new Model.Cell();
        cell28 = new Model.Cell();
        cell29 = new Model.Cell();
        cell30 = new Model.Cell();
        cell31 = new Model.Cell();
        cell32 = new Model.Cell();
        cell33 = new Model.Cell();
        cell34 = new Model.Cell();
        cell35 = new Model.Cell();
        cell36 = new Model.Cell();
        cell37 = new Model.Cell();
        cell38 = new Model.Cell();
        cell39 = new Model.Cell();
        cell40 = new Model.Cell();
        cell41 = new Model.Cell();
        cell42 = new Model.Cell();
        cell43 = new Model.Cell();
        cell44 = new Model.Cell();
        cell45 = new Model.Cell();
        cell46 = new Model.Cell();
        cell47 = new Model.Cell();
        cell48 = new Model.Cell();
        cell49 = new Model.Cell();

        setLayout(new java.awt.GridLayout(7, 7));

        sun.setForeground(new java.awt.Color(255, 51, 51));
        sun.setText("Sun");
        sun.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sunActionPerformed(evt);
            }
        });
        add(sun);

        mon.setText("Mon");
        mon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monActionPerformed(evt);
            }
        });
        add(mon);

        tues.setText("Tues");
        tues.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(tues);

        wed.setText("Wed");
        wed.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(wed);

        thurs.setText("Thurs");
        thurs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        thurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thursActionPerformed(evt);
            }
        });
        add(thurs);

        fri.setText("Fri");
        fri.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(fri);

        sat.setText("Sat");
        sat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satActionPerformed(evt);
            }
        });
        add(sat);

        cell8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell8);

        cell9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell9);

        cell10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell10);

        cell11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell11);

        cell12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell12);

        cell13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell13);

        cell14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell14);

        cell15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell15);

        cell16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell16);

        cell17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell17);

        cell18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell18);

        cell19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell19);

        cell20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell20);

        cell21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell21);

        cell22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell22);

        cell23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell23);

        cell24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell24);

        cell25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell25);

        cell26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell26);

        cell27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell27);

        cell28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell28);

        cell29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell29);

        cell30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell30);

        cell31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell31);

        cell32.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell32);

        cell33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell33);

        cell34.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell34);

        cell35.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell35);

        cell36.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell36);

        cell37.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell37);

        cell38.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell38);

        cell39.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell39);

        cell40.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell40);

        cell41.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell41);

        cell42.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell42);

        cell43.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell43);

        cell44.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell44);

        cell45.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell45);

        cell46.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell46);

        cell47.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell47);

        cell48.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell48);

        cell49.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(cell49);
    }// </editor-fold>//GEN-END:initComponents

    private void sunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sunActionPerformed

    private void thursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thursActionPerformed

    private void monActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monActionPerformed

    private void satActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_satActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Model.Cell cell10;
    private Model.Cell cell11;
    private Model.Cell cell12;
    private Model.Cell cell13;
    private Model.Cell cell14;
    private Model.Cell cell15;
    private Model.Cell cell16;
    private Model.Cell cell17;
    private Model.Cell cell18;
    private Model.Cell cell19;
    private Model.Cell cell20;
    private Model.Cell cell21;
    private Model.Cell cell22;
    private Model.Cell cell23;
    private Model.Cell cell24;
    private Model.Cell cell25;
    private Model.Cell cell26;
    private Model.Cell cell27;
    private Model.Cell cell28;
    private Model.Cell cell29;
    private Model.Cell cell30;
    private Model.Cell cell31;
    private Model.Cell cell32;
    private Model.Cell cell33;
    private Model.Cell cell34;
    private Model.Cell cell35;
    private Model.Cell cell36;
    private Model.Cell cell37;
    private Model.Cell cell38;
    private Model.Cell cell39;
    private Model.Cell cell40;
    private Model.Cell cell41;
    private Model.Cell cell42;
    private Model.Cell cell43;
    private Model.Cell cell44;
    private Model.Cell cell45;
    private Model.Cell cell46;
    private Model.Cell cell47;
    private Model.Cell cell48;
    private Model.Cell cell49;
    private Model.Cell cell8;
    private Model.Cell cell9;
    private Model.Cell fri;
    private Model.Cell mon;
    private Model.Cell sat;
    private Model.Cell sun;
    private Model.Cell thurs;
    private Model.Cell tues;
    private Model.Cell wed;
    // End of variables declaration//GEN-END:variables
}
