/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import Model.Day;
import java.awt.Color;
import java.time.LocalDate;
import java.util.ArrayList;

/**
 *
 * @author sidneylawther
 * 
 * credits: Ra Ven  https://www.youtube.com/watch?v=Y_T4YH9c6uw&t=240s
 * (ProgressGraph)
 */
public class DayView extends javax.swing.JPanel {

    /**
     * Creates new form DayView
     */
    public DayView() {
        initComponents();
        progressGraph1.addLegend("Work Duration", new Color(255, 204, 204));
        progressGraph1.addLegend("Rest Duration", new Color(204, 204, 255));
        
    }
    /* 
    adds in the set of data into the graph
    */
    public void generateGraph(Day data) {
        removeData();
        int hoursStudy = data.durationStudy;
        int hoursRest = data.durationRest;
        LocalDate date = data.getLocalDate();
        progressGraph1.addData(new ChartStuff.ModelChart(date.toString(), new double[]{hoursStudy, hoursRest}));
    }
    
    /*
    clears the bars from the graph
    */
    private void removeData() {
        progressGraph1.clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressGraph1 = new Components.ProgressGraph();

        setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(progressGraph1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(progressGraph1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.ProgressGraph progressGraph1;
    // End of variables declaration//GEN-END:variables
}
