/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import java.awt.Color;
import java.awt.Frame;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JFrame;
import javax.swing.WindowConstants;

/**
 *
 * @author peach
 */
public class MoveableTopBar extends javax.swing.JPanel {

    /**
     * Creates new form MoveableTopBar
     */
    
    private JFrame frame;
    public MoveableTopBar() {
        initComponents();
    }
    
    public void setFrame(JFrame frame) {
        this.frame = frame;
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMoving = new javax.swing.JPanel();
        closeButton1 = new UIStuff.CloseButton();
        minimizeButton1 = new UIStuff.MinimizeButton();

        setOpaque(false);

        panelMoving.setForeground(new java.awt.Color(255, 153, 51));
        panelMoving.setOpaque(false);

        closeButton1.setBorderPainted(false);
        closeButton1.setFocusable(false);
        closeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButton1ActionPerformed(evt);
            }
        });

        minimizeButton1.setBorderPainted(false);
        minimizeButton1.setFocusPainted(false);
        minimizeButton1.setFocusable(false);
        minimizeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMovingLayout = new javax.swing.GroupLayout(panelMoving);
        panelMoving.setLayout(panelMovingLayout);
        panelMovingLayout.setHorizontalGroup(
            panelMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMovingLayout.createSequentialGroup()
                .addGap(0, 857, Short.MAX_VALUE)
                .addComponent(minimizeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(closeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelMovingLayout.setVerticalGroup(
            panelMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(closeButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
            .addComponent(minimizeButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMoving, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMoving, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void topBarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topBarButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_topBarButton1ActionPerformed

    private void closeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButton1ActionPerformed
        // TODO add your handling code here:
        frame.dispose();
        System.exit(0);
    }//GEN-LAST:event_closeButton1ActionPerformed

    private void minimizeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeButton1ActionPerformed
        frame.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minimizeButton1ActionPerformed

    
    @Override
    protected void paintChildren(Graphics g) {
        Graphics2D g2 = (Graphics2D)g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(new Color(190, 90, 131));
        g2.fillRoundRect(0,0, getWidth(), getHeight(), 15,15);
        g2.fillRect(0, getHeight()-20, getWidth(), getHeight());
        super.paintChildren(g);
    }
    
    
    
    private int x;
    private int y; 

    public void initMoving(JFrame frame) {
        panelMoving.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent me) {
                x = me.getX();
                y = me.getY();
            }
        });
        
        panelMoving.addMouseMotionListener(new MouseMotionAdapter() {
            @Override 
            public void mouseDragged(MouseEvent me) {
                frame.setLocation(me.getXOnScreen()-x, me.getYOnScreen()-y);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private UIStuff.CloseButton closeButton1;
    private UIStuff.MinimizeButton minimizeButton1;
    private javax.swing.JPanel panelMoving;
    // End of variables declaration//GEN-END:variables
}
