/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import CurveChartStuff.ModelChart;
import java.time.LocalDate;

/**
 *
 * @author sidneylawther
 */
public class ProgressGraphCurved extends javax.swing.JPanel {

    /**
     * Creates new form ProgressGraphCurved
     */
    public ProgressGraphCurved() {
        initComponents();
        chart.setBackground(new Color(255, 255, 255));
        //chart.setTitle("Chart Data");
        chart.addLegend("Rest",  new Color(204, 204, 255),  new Color(204, 204, 255));
        chart.addLegend("Study", new Color(255, 204, 204), new Color(255, 204, 204));
        chart.clear();
        /*chart.addData(new ModelChart("January", new double[]{500, 50, 100}));
        chart.addData(new ModelChart("February", new double[]{600, 300, 150}));
        chart.addData(new ModelChart("March", new double[]{200, 50, 900}));
        chart.addData(new ModelChart("April", new double[]{480, 700, 100}));
        chart.addData(new ModelChart("May", new double[]{350, 540, 500}));
        chart.addData(new ModelChart("June", new double[]{450, 800, 100}));*/
        chart.start();
    }
    
    public void clear() {
        chart.clear();
    }
    
    public void generateGraph(ArrayList<Model.Day> data) {
        chart.clear();
        for (int i = 0; i < data.size(); i++) {
            int hoursStudy = data.get(i).durationStudy;
            int hoursRest = data.get(i).durationRest;
            LocalDate date = data.get(i).date;
            if (date.getDayOfMonth() == date.lengthOfMonth() / 2) {
                chart.addData(new ModelChart("", new double[]{hoursStudy, hoursRest}));
            } else {
                chart.addData(new ModelChart("", new double[]{hoursStudy, hoursRest}));
            }
        chart.start();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chart = new CurveChartStuff.CurveLineChart();

        chart.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public CurveChartStuff.CurveLineChart chart;
    // End of variables declaration//GEN-END:variables
}
