/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;
import Data.TimerData;
import Panel.*;
import Model.TimerSpecification;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.DefaultComboBoxModel;

 
/**
 *
 * @author peach
 */
public class StartTimer extends javax.swing.JPanel implements ActionListener {
    //Stuff needed for the Timer and timer logic 
    Timer timer = new Timer(1000, this);
    int k = 0;
    static int studyDurationInt = 0;
    static int restDurationInt = 0;
    static boolean isWorking = true;
    boolean extendedWork = false;
    boolean extendedRest = false;
    private static TimerSpecification[] options; 
    
    
    //**Components for notifications (appear at end of session)**//
    JFrame frame2 = new JFrame();
    JLabel label3 = new JLabel("Work Period over!");
    JPanel panel5 = new JPanel();
    JButton button4 = new JButton("5 more minutes");
    JButton button5 = new JButton("Time to rest!");
    
    JFrame frame3 = new JFrame();
    JLabel label4 = new JLabel("Rest is over!");
    JPanel panel6 = new JPanel();
    JButton button6 = new JButton("5 more minutes");
    JButton button7 = new JButton("Ready for Work!");
    

    /**
     * Creates new form FormTimer
     */
    public StartTimer() {
        options = TimerData.getTimers();
        initComponents();
    }
    
    
    // Timer logic eg updating the JLabel that indicates the time every minute //
    @Override
    public void actionPerformed(ActionEvent e) {     
        if (e.getSource() == timer) {
            k++;
            updateTime(k);
            currentStage.setText(isWorking? "Work Period" : "Rest Period");
            
            if(extendedWork && k == 5 + studyDurationInt) {
                extendedWork = false;
                timer.stop();
                moveToRest();
            }
            else if(extendedRest && k == 5 + restDurationInt) {
                extendedRest = false;
                timer.stop();
                moveToWork();
            }
            
            
            else if(isWorking && k  == studyDurationInt) {
                timer.stop();
                moveToRest();
                
            }
            
            else if (!isWorking && k == restDurationInt) {
                timer.stop();
                moveToWork();              
            }
            
        
        } if (e.getSource() == button4) { // user presses the button to extend study
            extendedWork = true;
            timer.start();
            frame2.dispose();
            button4.setEnabled(false);
        }
        
        if (e.getSource() == button5) {  // user choses to move into rest session
            ProgressPanel.updateStudy(k);
            k = 0;
            timer.start();
            isWorking = false;
            frame2.dispose();
            button4.setEnabled(true);
        }
        if (e.getSource() == button6) { // user presses the button to extend rest
            extendedRest = true;
            timer.start();
            frame3.dispose();
            button6.setEnabled(false);
            
            
        }
        if (e.getSource() == button7) { //user choses to move into work session
            
            ProgressPanel.updateRest(k);
            k = 0;
            timer.start();
            isWorking = true;
            frame3.dispose();
            button6.setEnabled(true);
            
        }
            
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>(options);
        currentStage = new javax.swing.JLabel();
        circleProgressBar1 = new CircleProgress.CircleProgressBar();
        jButton3 = new javax.swing.JButton();

        setOpaque(false);

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Stop");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Timer:");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        currentStage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        circleProgressBar1.setBackground(new java.awt.Color(242, 242, 242));
        circleProgressBar1.setForeground(new java.awt.Color(0, 0, 0));

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(165, 165, 165)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(currentStage, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(circleProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(44, 44, 44)
                                .addComponent(jButton2)))))
                .addGap(0, 73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentStage, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(circleProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(238, Short.MAX_VALUE))
        );

        circleProgressBar1.setString("");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        currentStage.setText(isWorking? "Work Period" : "Rest Period");
        TimerSpecification timerUsed = (TimerSpecification) jComboBox1.getSelectedItem();
        studyDurationInt = timerUsed.studyTime * 60;
        restDurationInt = timerUsed.breakTime * 60;
        //Panel.ProgressPanel.addDate(LocalDate.now());
        Data.DaysData.addDate(LocalDate.now());
        timer.start();
        jButton1.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        timer.stop();
        if (isWorking) {
            ProgressPanel.updateStudy(k);
        } else if (!isWorking) {
            ProgressPanel.updateRest(k);
        }
        
        k = 0;
        updateTime(k);
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        Model.TimerSpecification timerChosen =(TimerSpecification) jComboBox1.getSelectedItem();
        CreateTimer.setSlidersToTimer(timerChosen);
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        TimerSpecification ts = (TimerSpecification) jComboBox1.getSelectedItem();
        jComboBox1.removeItem(ts);
        Data.TimerData.deleteTimer(ts);
        System.out.println(jComboBox1.getSelectedIndex());
    }//GEN-LAST:event_jButton3ActionPerformed

    
    //helper functions
    private static String mins(int k) {
        if ((k / 60) < 10) {
            return "0" + (k / 60);
        } else {
            return k / 60 + "";
        }
    }
    
    private static String secs(int k) {
        
        if (k - ((k / 60) * 60) < 10) {
            return "0" + (k - ((k / 60) * 60));
        } else {
            return k - ((k / 60) * 60) + "";
        }
    }
    
    
    // notification frame for end of study session, users can either press the button to move to rest or extend work   
    private void moveToRest() {
        frame2.setSize(300, 120);
        frame2.setLayout(new FlowLayout(3));
        
        button4.addActionListener(this);
        button5.addActionListener(this);
        panel5.add(button4);
        panel5.add(button5);
        frame2.add(label3);
        frame2.add(panel5);
        frame2.setVisible(true);
    }
    
    // notification frame for end of rest session, users can either press the button to move to work or extend rest
    private void moveToWork() {
        
        frame3.setSize(300, 120);
        frame3.setLayout(new FlowLayout(3));
        
        button6.addActionListener(this);
        button7.addActionListener(this);
        panel6.add(button6);
        panel6.add(button7);
        frame3.add(label4);
        frame3.add(panel6);
        frame3.setVisible(true);
    }
    
    //helper function tp update the combox box whena  new custom timer is created
    public static void addTimer(TimerSpecification tS) {
        TimerData.addTimer(tS);
        options = TimerData.getTimers();
        jComboBox1.setModel(new DefaultComboBoxModel<>(options));
    }
    
    //updating the graphics used to display time as each minute passes
    private static void updateTime(int k) {
        System.out.println(k);
        circleProgressBar1.setText(String.valueOf(mins(k) + ":" + secs(k)));
        if (isWorking) {
            double persentage1 = ((double) k / (double) studyDurationInt);
            circleProgressBar1.setValue((int) Math.round(persentage1 * 100));
            circleProgressBar1.setForeground(new Color(255, 204, 204));

        } else {
            double persentage2 = ((double) k / (double) restDurationInt);
            circleProgressBar1.setValue((int) Math.round(persentage2 * 100));
            circleProgressBar1.setForeground(new Color(204, 204, 255));

        }
    }
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static CircleProgress.CircleProgressBar circleProgressBar1;
    private javax.swing.JLabel currentStage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public static javax.swing.JComboBox<Model.TimerSpecification> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
