/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;
import Panel.*;
import Model.TimerSpecification;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.Timer;
import java.time.LocalDate;

 
/**
 *
 * @author peach
 */
public class StartTimer1 extends javax.swing.JPanel implements ActionListener {
    Timer timer = new Timer(100, this);
    int k = 0;
    int studyDurationInt = 0;
    int restDurationInt = 0;
    boolean isWorking = true;
    boolean extendedWork = false;
    boolean extendedRest = false;
    
    
    JFrame frame2 = new JFrame();
    JLabel label3 = new JLabel("Work Period over!");
    JPanel panel5 = new JPanel();
    JButton button4 = new JButton("5 more minutes");
    JButton button5 = new JButton("Time to rest!");
    
    JFrame frame3 = new JFrame();
    JLabel label4 = new JLabel("Rest is over!");
    JPanel panel6 = new JPanel();
    JButton button6 = new JButton("5 more minutes");
    JButton button7 = new JButton("Ready for Work!");
    
    
    Model.TimerSpecification defaultPomodoro = new Model.TimerSpecification("Pomodoro Timer", 25,5);
    Model.TimerSpecification[] options = {defaultPomodoro};    
    

    /**
     * Creates new form FormTimer
     */
    public StartTimer1() {
        initComponents();
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {     
        if (e.getSource() == timer) {
            k++;
            //jLabel1.setText(String.valueOf(mins(k) + ":" + secs(k)));
            updateTime(k);
            currentStage.setText(isWorking? "Work Period" : "Rest Period");
        
            
            
            
            if(extendedWork && k == 5 + studyDurationInt) {
                extendedWork = false;
                timer.stop();
                moveToRest();
            }
            else if(extendedRest && k == 5 + restDurationInt) {
                extendedRest = false;
                timer.stop();
                moveToWork();
            }
            
            
            else if(isWorking && k  == studyDurationInt) {
                timer.stop();
                moveToRest();
                //isWorking = false;
                //System.out.println(k);
            }
            
            else if (!isWorking && k == restDurationInt) {
                timer.stop();
                //isWorking = true;
                moveToWork();
                
                
            }
            
        // buttons that appear in the notifications
        } if (e.getSource() == button4) { //extend study
            extendedWork = true;
            timer.start();
            frame2.dispose();
            button4.setEnabled(false);
        }
        
        if (e.getSource() == button5) {  
            //ProgressPanel.timeStudy = ProgressPanel.timeStudy + k;
            ProgressPanel.updateStudy(k);
            k = 0;
            timer.start();
            isWorking = false;
            frame2.dispose();
            button4.setEnabled(true);
        }
        if (e.getSource() == button6) { // extend rest
            extendedRest = true;
            timer.start();
            frame3.dispose();
            button6.setEnabled(false);
            
            
        }
        if (e.getSource() == button7) { //move to work
            //ProgressPanel.timeRest = ProgressPanel.timeRest + k;
            ProgressPanel.updateRest(k);
            k = 0;
            timer.start();
            isWorking = true;
            frame3.dispose();
            button6.setEnabled(true);
            
        }
            
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>(options);
        currentStage = new javax.swing.JLabel();

        setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("00:00");

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Stop");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Timer:");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        currentStage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(131, 131, 131))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(currentStage, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(168, 168, 168)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jButton1)
                        .addGap(44, 44, 44)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(28, 28, 28)
                .addComponent(currentStage, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(234, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        currentStage.setText(isWorking? "Work Period" : "Rest Period");
        TimerSpecification timerUsed = (TimerSpecification) jComboBox1.getSelectedItem();
        studyDurationInt = timerUsed.studyTime;
        restDurationInt = timerUsed.breakTime;
        Panel.ProgressPanel.addDate(LocalDate.now());
        timer.start();
        jButton1.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        timer.stop();
        if (isWorking) {
            //ProgressPanel.timeStudy = ProgressPanel.timeStudy + k;
            ProgressPanel.updateStudy(k);
        } else if (!isWorking) {
            //ProgressPanel.timeRest = ProgressPanel.timeRest + k;
            ProgressPanel.updateRest(k);
        }
        
        k = 0;
        updateTime(k);
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        Model.TimerSpecification timerChosen =(TimerSpecification) jComboBox1.getSelectedItem();
        CreateTimer1.setSlidersToTimer(timerChosen);
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    
    //helper functions
    private static String mins(int k) {
        if ((k / 60) < 10) {
            return "0" + (k / 60);
        } else {
            return k / 60 + "";
        }
    }
    
    private static String secs(int k) {
        
        if (k - ((k / 60) * 60) < 10) {
            return "0" + (k - ((k / 60) * 60));
        } else {
            return k - ((k / 60) * 60) + "";
        }
    }
    
    
    private void moveToRest() {
        
        
        frame2.setTitle("Timer");
        frame2.setSize(300, 120);
        frame2.setLayout(new FlowLayout(3));
        
        button4.addActionListener(this);
        button5.addActionListener(this);
        panel5.add(button4);
        panel5.add(button5);
        frame2.add(label3);
        frame2.add(panel5);
        frame2.setVisible(true);
    }
    
    private void moveToWork() {
        
        frame3.setSize(300, 120);
        frame3.setLayout(new FlowLayout(3));
        
        button6.addActionListener(this);
        button7.addActionListener(this);
        panel6.add(button6);
        panel6.add(button7);
        frame3.add(label4);
        frame3.add(panel6);
        frame3.setVisible(true);
    }
    
    public static void addTimer(Model.TimerSpecification tS) {
        jComboBox1.addItem(tS);
    }
    
    private static void updateTime(int k) {
        jLabel1.setText(String.valueOf(mins(k) + ":" + secs(k)));
    }
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentStage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public static javax.swing.JComboBox<Model.TimerSpecification> jComboBox1;
    private static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
