/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import Data.MainTasksData;
import Model.MainTask;
import Model.SubTask;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.Timer;

/**
 *
 * @author peach
 */
public class SubTasksComponent extends javax.swing.JPanel {

    /**
     * Creates new form SubTasksInput
     */
    private int numOfSubtasks = 1;
    private MainTask mainTask;
    private ArrayList<SubTaskInput> subTaskInputs;
    private Timer timer;
    
    final private Color REDWARNING = new Color(153, 2, 60);
    final private Color YELLOWWARNING = new Color(204, 136, 0);
    final private Color GREENWARNING = new Color(0, 145, 10);
    
    
    public SubTasksComponent() {
        initComponents();
        subTaskInputs = new ArrayList<>();
       
        SubTaskInput subTaskInput = new SubTaskInput();
        subTaskInputs.add(subTaskInput);
        jPanel1.add(subTaskInput);
        
        numOfSubtasks = subTaskInputs.size();
        jPanel1.setLayout(new GridLayout(numOfSubtasks, 1));
        
        warning.setBackground(new Color(0,0,0,0));
        
        timer = new Timer(2000, (ActionEvent e) -> {
            warning.setText("");
        });
        timer.setRepeats(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addButton = new UIStuff.CustomColorButton();
        confirmButton = new UIStuff.CustomColorButton();
        scrollPaneWin111 = new RavenScrollBar.ScrollPaneWin11();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        deleteTask = new UIStuff.CustomColorButton();
        warning = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        addButton.setText("Add Sub Task");
        addButton.setBorderPainted(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        confirmButton.setText("Confirm");
        confirmButton.setBorderPainted(false);
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        scrollPaneWin111.setFocusable(false);

        jPanel1.setFocusable(false);
        jPanel1.setLayout(new java.awt.GridLayout(10, 1));
        scrollPaneWin111.setViewportView(jPanel1);

        jLabel1.setText("SubTask");

        deleteTask.setText("Delete Sub Task");
        deleteTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTaskActionPerformed(evt);
            }
        });

        warning.setText("  ");

        jLabel2.setText("Deadline");

        jLabel3.setText("Weight");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollPaneWin111, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(warning, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(warning, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollPaneWin111, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        numOfSubtasks++;
        jPanel1.setLayout(new GridLayout(numOfSubtasks, 1));
        SubTaskInput subTaskInput = new SubTaskInput();
        subTaskInputs.add(subTaskInput);
        jPanel1.add(subTaskInput);
        System.out.println("subtask added");
        jPanel1.revalidate();
        jPanel1.repaint();
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTaskActionPerformed
        if (numOfSubtasks > 1) {
            numOfSubtasks--;
            jPanel1.setLayout(new GridLayout(numOfSubtasks, 1));
            jPanel1.remove(subTaskInputs.get(numOfSubtasks - 1));
            subTaskInputs.remove(subTaskInputs.size() - 1);
             System.out.println("subtask removed");
            jPanel1.revalidate();
            jPanel1.repaint();
        } else {
            setWarningText("<html>1 SubTask minimum</html>", REDWARNING);
        }
    }//GEN-LAST:event_deleteTaskActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed

        if (mainTask.task != null && mainTask.deadline != null) {
                for (int i = 0; i < numOfSubtasks; i++) {
                SubTaskInput subTaskInput = subTaskInputs.get(i);
                if (!subTaskInput.isAdded()) {
                    if (!subTaskInput.getTask().trim().isEmpty()) {
                        mainTask.addSubTask(new SubTask(subTaskInput.getTask(), subTaskInput.getDate(), subTaskInput.getWeight()));
                        subTaskInput.toggleAdded();
                    }
                }
            }

            MainTasksData.addTask(mainTask);
            
            setWarningText("<html> Main Task:" + mainTask.getTask() 
                    + " has been added with " + mainTask.subTasks.size() + " subtasks. Please refresh the calendar to view new heatmap." , GREENWARNING, 5);
            
         } else {
            setWarningText("<html>Please input a main task and choose the deadline</html>", YELLOWWARNING, 4);
        }
       
       
    }//GEN-LAST:event_confirmButtonActionPerformed

    public void setMainTask(MainTask mainTask) {
        this.mainTask = mainTask;
    }
    
    private void setWarningText(String string, Color color) {
        warning.setText(string);
        warning.setForeground(color);
        timer.start();
    }
    
    private void setWarningText(String string, Color color, int delay) {
        warning.setText(string);
        warning.setForeground(color);
        timer.setDelay(delay * 1000);
        timer.start();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private UIStuff.CustomColorButton addButton;
    private UIStuff.CustomColorButton confirmButton;
    private UIStuff.CustomColorButton deleteTask;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private RavenScrollBar.ScrollPaneWin11 scrollPaneWin111;
    private javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables
}
