/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import Model.SubTask;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.Timer;

/**
 *
 * @author peach
 */
public class SubTasksComponent extends javax.swing.JLayeredPane {

    /**
     * Creates new form SubTasksInput
     */
    private final ArrayList<SubTaskInput> subTaskInputs;

    
    public SubTasksComponent() {
        initComponents();
        
        subTaskInputs = new ArrayList<>();
       
        SubTaskInput subTaskInput = new SubTaskInput();
        
        subTaskInputs.add(subTaskInput);
        jLayeredPane1.add(subTaskInput);
  
        jLayeredPane1.setLayout(new GridLayout(subTaskInputs.size(), 1));
        
        warning.setBackground(new Color(0,0,0,0));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addButton = new UIStuff.CustomColorButton();
        scrollPaneWin111 = new RavenScrollBar.ScrollPaneWin11();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        deleteButton = new UIStuff.CustomColorButton();
        warning = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        addButton.setText("Add Sub Task");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        scrollPaneWin111.setBackground(new java.awt.Color(250, 232, 233));
        scrollPaneWin111.setFocusable(false);

        jLayeredPane1.setBackground(new java.awt.Color(250, 232, 233));
        jLayeredPane1.setForeground(new java.awt.Color(250, 232, 233));

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        scrollPaneWin111.setViewportView(jLayeredPane1);

        jLabel1.setText("SubTask");

        deleteButton.setText("Delete Sub Task");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        warning.setText("  ");

        jLabel2.setText("Deadline");

        jLabel3.setText("Weight");

        setLayer(addButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        setLayer(scrollPaneWin111, javax.swing.JLayeredPane.DEFAULT_LAYER);
        setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        setLayer(deleteButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        setLayer(warning, javax.swing.JLayeredPane.DEFAULT_LAYER);
        setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollPaneWin111, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(warning, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(warning, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        jLayeredPane1.setLayout(new GridLayout(subTaskInputs.size()+1, 1));
        SubTaskInput subTaskInput = new SubTaskInput();
        subTaskInputs.add(subTaskInput);
        jLayeredPane1.add(subTaskInput);
        System.out.println("subtask input box added");
        jLayeredPane1.revalidate();
        jLayeredPane1.repaint();
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if (subTaskInputs.size() > 1) {
            jLayeredPane1.setLayout(new GridLayout(subTaskInputs.size()-1, 1));
            jLayeredPane1.remove(subTaskInputs.get(subTaskInputs.size() - 1));
            subTaskInputs.remove(subTaskInputs.size() - 1);
             System.out.println("subtask input box removed");
            jLayeredPane1.revalidate();
            jLayeredPane1.repaint();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    public ArrayList<SubTask> getSubtasks() {
        ArrayList<SubTask> subtasks = new ArrayList();
        for (int i = 0; i < subTaskInputs.size(); i++) {
            SubTaskInput subTaskInput = subTaskInputs.get(i);
            if (!subTaskInput.getTask().trim().isEmpty() && subTaskInput.getDate() != null) {
                subtasks.add(new SubTask(subTaskInput.getTask(), subTaskInput.getDate(), subTaskInput.getWeight()));
            }
        }
        
        return subtasks;
    }
    
    public void setSubtasks(ArrayList<SubTask> subtasks) {
        jLayeredPane1.removeAll();
        jLayeredPane1.setLayout(new GridLayout(subtasks.size(), 1));
        for (SubTask subTask : subtasks) {
            SubTaskInput subTaskInput = new SubTaskInput(subTask);
            jLayeredPane1.add(subTaskInput);
            subTaskInputs.add(subTaskInput);
        }
        
        jLayeredPane1.revalidate();
        jLayeredPane1.repaint();
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private UIStuff.CustomColorButton addButton;
    private UIStuff.CustomColorButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private RavenScrollBar.ScrollPaneWin11 scrollPaneWin111;
    private javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables
}
