/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import Model.SubTask;
import com.toedter.calendar.JTextFieldDateEditor;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author peach
 */
public class SubTaskInput extends javax.swing.JPanel {

    /**
     * Creates new form SubTaskInput
     */
    
    private boolean added;
    
    public SubTaskInput() {
        initComponents();
        init();
        
        Calendar calendar = Calendar.getInstance();
        jDateChooser1.setDate(calendar.getTime());
        jDateChooser1.getJCalendar().setMinSelectableDate(calendar.getTime());
        setOpaque(false);
    }
    
    public SubTaskInput(SubTask subTask) {
        initComponents();
        init();
        coloredTextBox1.setText(subTask.task);
        jDateChooser1.setDate(subTask.deadline);
        jSpinner1.setValue(subTask.weight);
        setOpaque(false);
    }
    
    private void init() {
        coloredTextBox1.setLimit(70);
        JTextFieldDateEditor editor = (JTextFieldDateEditor) jDateChooser1.getDateEditor();
        editor.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        coloredTextBox1 = new UIStuff.ColoredTextBox();
        jSpinner1 = new javax.swing.JSpinner();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        coloredTextBox1.setText(" ");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(coloredTextBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coloredTextBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    protected String getTask () {
        return coloredTextBox1.getText();
    }
    protected Date getDate() {
        return jDateChooser1.getDate();
    }
    
    protected int getWeight() {
        return (int) jSpinner1.getValue();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private UIStuff.ColoredTextBox coloredTextBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
