/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import Data.MainTasksData;
import Manage.ManagePanel;
import Model.MainTask;
import Model.SubTask;
import UIStuff.ClickableTask;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JLabel;
import org.joda.time.DateTimeComparator;

/**
 *
 * @author peach
 */
public class TaskView extends javax.swing.JPanel {

    private static ArrayList<MainTask> mainTasks;
    private final GridBagConstraints c;
            
    /**
     * Creates new form TaskView
     */
    public TaskView() {
        initComponents();
        setLayout(new GridBagLayout());
        c = new GridBagConstraints();
        initialText();
        setOpaque(false);
        setVisible(true);
    }
    
    public void setTasks(Date date) {
        removeAll();
        DateTimeComparator dateTimeComparator = DateTimeComparator.getDateOnlyInstance();
        
        c.gridy = 0;
        add(new TaskViewHeader(), c);
        c.gridy = 1;
        
        mainTasks = MainTasksData.getMainTasks();
        if (mainTasks.isEmpty()) {
            noTasks();
        } else {
            for (int i=0; i < mainTasks.size(); i++ ){
                if (dateTimeComparator.compare(date, mainTasks.get(i).deadline)== 0) {
                    ClickableTask clickableTask = new ClickableTask(mainTasks.get(i), i);
                    c.gridy++;
                    add(clickableTask,c);
                } else {
                    for (SubTask subtask : mainTasks.get(i).subTasks) {
                        if (dateTimeComparator.compare(date, subtask.deadline)== 0) {
                            ClickableTask clickableTask = new ClickableTask(mainTasks.get(i), i);
                            c.gridy++;
                            add(clickableTask,c);
                        }
                    }
                }
                revalidate();
                repaint();
                setVisible(true);
            } 
        }
    }
    
    private String substring(String text, int length) {
        String[] results = text.split("(?<=\\G.{" + length + "})");

        return results[0];
    }
    

    public void updateTasks() {
        removeAll();
        c.gridy = 0;
        add(new TaskViewHeader(), c);
        c.gridy = 1;
        
        mainTasks = MainTasksData.getMainTasks();
        
        if (!mainTasks.isEmpty()) {
            for (int i=0; i < mainTasks.size(); i++ ){
                if (mainTasks.get(i).task.length() > 62) {
                        System.out.println("I see you edited a task illegally... well no matter, I'll just cut down to 62 characters.");
                        mainTasks.get(i).task = substring(mainTasks.get(i).task, 62);
                        MainTasksData.saveTasks();
                }
                ClickableTask clickableTask = new ClickableTask(mainTasks.get(i), i);
                c.gridy++;
                add(clickableTask,c);
            } 
            revalidate();
            repaint();
            setVisible(true);
        } else
            noTasks();
    }
    
    public void noTasks() {
        removeAll();
        c.gridy = 0;
        JLabel noTasksLabel = new JLabel("No Tasks Due On This Day");
        
        add(noTasksLabel, c);
        
        revalidate();
        repaint();
        setVisible(true);
    }
    
    public void initialText() {
        removeAll();
        c.gridy = 0;
        JLabel noTasksLabel = new JLabel("Click on any date to view subtasks or main tasks due that day.");
        
        add(noTasksLabel, c);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 966, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
