/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import Model.MainTask;
import Model.SubTask;
import UIStuff.MainTaskItem;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.ArrayList;

/**
 *
 * @author peach
 */
public class TaskView extends javax.swing.JPanel {

    private static ArrayList<MainTask> mainTasks;
    private GridBagConstraints c;
            
    /**
     * Creates new form TaskView
     */
    public TaskView() {
        initComponents();
        setLayout(new GridBagLayout());
        c = new GridBagConstraints();
        
        setOpaque(false);
        setVisible(true);
    }
    
    public void setTasks(ArrayList<MainTask> mainTasks) {
        TaskView.mainTasks = mainTasks; 

        updateTasks();
        System.out.println(mainTasks.size());
    }
    
    public void updateTasks() {
        removeAll();
        c.gridy = 0;
        //System.out.println(mainTasks.size());
         for (int i=0; i < mainTasks.size(); i++ ){
            MainTaskItem taskItem = new MainTaskItem(mainTasks.get(i));
            UIStuff.ClickableTask clickableTask = new UIStuff.ClickableTask(taskItem);
            c.gridy++;
            add(clickableTask,c);
        } 
        setVisible(true);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 966, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
