/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import Model.MainTask;
import Model.SubTask;
import UIStuff.MainTaskItem;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.util.ArrayList;

/**
 *
 * @author peach
 */
public class TaskView extends javax.swing.JPanel {

    public ArrayList<MainTask> mainTasks = new ArrayList();
            
    /**
     * Creates new form TaskView
     */
    public TaskView() {
        initComponents();
        setLayout(new FlowLayout());
        
        setPreferredSize(new Dimension(570, 2000));
        
        /**
         * For testing purposes
         */
        initData(mainTasks);
        
        
        for (int i=0; i < mainTasks.size(); i++ ){
            MainTaskItem taskItem = new MainTaskItem(mainTasks.get(i));
            UIStuff.ClickableTask clickableTask = new UIStuff.ClickableTask(taskItem);
            add(clickableTask);
        } 
        
        
        setOpaque(false);
        setVisible(true);
    }

    
    private void initData(ArrayList<MainTask> mainTasks) {
        for (int i = 1; i < 10; i++) {
            ArrayList<SubTask> subtasks = new ArrayList();
            for (int j = 1; j < 5; j ++) {
                subtasks.add(new SubTask("Subtask " + j, j + "/7/2023", j));
            }
            
            mainTasks.add(new MainTask("Task " + i, i + "/7/2023", 2, subtasks));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 966, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
