/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import java.awt.Color;
import java.time.LocalDate;
import java.util.ArrayList;

/**
 *
 * @author sidneylawther
 */
public class WeekView extends javax.swing.JPanel {

    /**
     * Creates new form WeekView
     */
    public WeekView() {
        initComponents();
        initComponents();
        progressGraph1.addLegend("Work Duration", new Color(255, 204, 204));
        progressGraph1.addLegend("Rest Duration", new Color(204, 204, 255));
    }
    
    public void generateGraph(ArrayList<Model.Day> data) {
        for (int i = 0; i < data.size(); i++) {
            int hoursStudy = data.get(i).durationStudy;
            int hoursRest = data.get(i).durationRest;
            LocalDate date = data.get(i).date;
            progressGraph1.addData(new ChartStuff.ModelChart(date.getDayOfWeek().toString(), new double[]{hoursStudy, hoursRest}));
        }
        
    }
    
    public void removeData() {
        progressGraph1.clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressGraph1 = new Components.ProgressGraph();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progressGraph1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progressGraph1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.ProgressGraph progressGraph1;
    // End of variables declaration//GEN-END:variables
}
