/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GameDetection;

import java.awt.Color;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author peach
 */
public class BouncingFrame extends javax.swing.JFrame {

    private int x;
    private int y;
    private int x_move = 10;
    private int y_move = 10;
    
    // Get the default screen device
    private static final GraphicsDevice graphicsDevice = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();

    // Get the current display mode of the screen
    // Get the screen dimensions
    private static final int SCREEN_WIDTH = graphicsDevice.getDisplayMode().getWidth();
    private static final int SCREEN_HEIGHT = graphicsDevice.getDisplayMode().getHeight();
    
    private final int N_OFFSET;
    private final int P_OFFSET;
    
    private final int MIN_SPEED = 3;
    private final int MAX_SPEED = 100;
    
    
    private final Timer timer;
    /**
     * Creates new form Test
     */
    public BouncingFrame(String filename, int nOffset, int pOffset) {
        this.N_OFFSET = nOffset;
        this.P_OFFSET = pOffset;
        
        Random r = new Random();
        x_move =  (r.nextInt(MAX_SPEED-MIN_SPEED) + MIN_SPEED);
        y_move = (r.nextInt(MAX_SPEED-MIN_SPEED) + MIN_SPEED);
        
        setUndecorated(true);
        initComponents();
        pack();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        
        jLabel1.setIcon(new ImageIcon(filename));
        setBackground(new Color(0,0,0,0));
        setAlwaysOnTop(true);
        setVisible(true);
        timer = new Timer(30, (ActionEvent e) -> {
            move();
        });
        
         //Timer stopTimer = new Timer(15000, (ActionEvent e) -> {
           //  timer.stop();
        //});
        //stopTimer.setRepeats(false);
        //stopTimer.start();
        
        timer.start();
        jLabel1.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent me) {
                x = me.getX();
                y = me.getY();
            }
         
        });
        
        jLabel1.addMouseMotionListener(new MouseMotionAdapter() {
            @Override 
            public void mouseDragged(MouseEvent me) {
                setLocation(me.getXOnScreen()-x, me.getYOnScreen()-y);
            }
        });
        


    }
   
    private void move() {
        if (x  > SCREEN_WIDTH - N_OFFSET) {
            Random r = new Random();
            x_move =  (r.nextInt(MAX_SPEED-MIN_SPEED) + MIN_SPEED) * (-1);
        } else if (y > SCREEN_HEIGHT - N_OFFSET) {
            Random r = new Random();
            y_move = (r.nextInt(MAX_SPEED-MIN_SPEED) + MIN_SPEED) * (-1);
        } else if (x < 0 - P_OFFSET) {
            Random r = new Random();
            x_move = (r.nextInt(MAX_SPEED-MIN_SPEED) + MIN_SPEED);
        } else if (y < 0 - P_OFFSET) {
            Random r = new Random();
            y_move = (r.nextInt(MAX_SPEED-MIN_SPEED) + MIN_SPEED);
        }
        
        x += x_move;
        y += y_move;
        setLocation(x, y);
        
    }
    
    @Override
    public void dispose() {
        // Stop the timer before disposing of the frame
        timer.stop();
        super.dispose();
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
