/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CleoDevelopmentver1;

import java.text.ParseException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws ParseException {
        System.out.println(new App().getGreeting());
        //new MainUI();
        new Main();
    }
}
