/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CleoDevelopmentver1;

import java.io.IOException;
import java.text.ParseException;

public class App {
    public String getGreeting() {
        return "Welcome to Cleo App!";
    }

    public static void main(String[] args) throws ParseException, IOException {
        System.out.println(new App().getGreeting());
        new Main();
        //new MainUI();
        //new JsonDecoder();
                
        //new BouncingFrame("animated/test.gif");
        //new BouncingFrame("animated/test2.gif");
        //new BouncingFrame("animated/cleo_idle.gif", 155, 70);
        //new BouncingFrame("animated/cleo_sit.gif", 155, 70);
        //new BouncingFrame("animated/cleo_sleep.gif", 155, 70);
        
        
        //GameDetection gameDetection = new GameDetection();
        //gameDetection.startDetection();
            /*Runnable task2 = () -> {
                Robot robot;   
                try {
                    robot = new Robot();
                    //pressing key by invoking the keyPress() method  
                    robot.keyPress(KeyEvent.VK_SPACE);   

                } catch (AWTException ex) {
                    Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
                }
            };
            */
                        
        
        
        
        /*
        String command = "notepad.exe";   
        Runtime run = Runtime.getRuntime();   
        run.exec(command);   
        try   
        {   
        //delay 4ms  
        Thread.sleep(4000);   
        }   
        catch (InterruptedException e)   
        {   
        // TODO Auto-generated catch block   
        e.printStackTrace();   
        }   
*/
        //creating a constructor of the Robot class  

        
        
    }
}
