/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panel;
//import static Panel.ProgressPanel.data;
import Data.DaysData;
import java.awt.Color;
import java.time.LocalDate;
import java.util.ArrayList;
/**
 *
 * @author sidneylawther
 */
public class ProgressPanel extends javax.swing.JPanel {
    public static ArrayList<Model.Day> data;
    
    public static int timeStudy = 0;
    public static int timeRest = 0;
            
    /**
     * Creates new form ProgressPanel1
     */
    public ProgressPanel() {
        initComponents();
        setOpaque(false);
        dayView1.setOpaque(false);
        weekView1.setOpaque(false);
        monthView1.setOpaque(false);
        
        data = DaysData.getDays();
        
        updateAllView(data);
        dayView1.setBounds(100, 100, dayView1.getWidth(), dayView1.getHeight());
        dayView1.setVisible(true);
        weekView1.setVisible(false);
        monthView1.setVisible(false);
        
        repaint();
                
        
    }
    
    public static void updateAllView(ArrayList<Model.Day> data) {
        updateWeekView(data);
        updateDayView(data);
        updateMonthView(data);

    }
    
    private static void updateDayView(ArrayList<Model.Day> data) {
        ArrayList<Model.Day> dataRefined = new ArrayList<>();
        data = DaysData.getDays();
        
        int k = 1;
        while (k != 0) {
            if (data.size() - k >= 0)
                dataRefined.add(data.get(data.size() - k));
            
            k--;
        }
        dayView1.removeData();
        dayView1.generateGraph(dataRefined);
    }
    
    private static void updateWeekView(ArrayList<Model.Day> data) {
        ArrayList<Model.Day> dataRefined = new ArrayList<>();
        data = DaysData.getDays();
        
        int k = 7;
        while (k != 0) {
            if (data.size() - k >= 0)
                dataRefined.add(data.get(data.size() - k));
            
            k--;
        }
        weekView1.removeData();
        weekView1.generateGraph(dataRefined);
    }
    
    private static void updateMonthView(ArrayList<Model.Day> data) {
        ArrayList<Model.Day> dataRefined = new ArrayList<>();
        data = DaysData.getDays();
        
        int k = LocalDate.now().lengthOfMonth();
        while (k != 0) {
            if (data.size() - k >= 0)
                dataRefined.add(data.get(data.size() - k));
            
            k--;
        }
        monthView1.generateGraph(dataRefined);
    }
    
    
    public static void updateStudy(int k) {
        ProgressPanel.timeStudy = ProgressPanel.timeStudy + k;
        //System.out.println(k);
        DaysData.updateTodayStudy(k);
        jLabel2.setText("Time Studying: "+ ProgressPanel.timeStudy);
        updateAllView(data);
        
    }
    
    public static void updateRest(int k) {
        Model.Day today = data.get(data.size() - 1);
        ProgressPanel.timeRest = ProgressPanel.timeRest + k;
        DaysData.updateTodayRest(k);
        jLabel1.setText("Time Resting: "+ ProgressPanel.timeRest);
        updateAllView(data);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        dayView1 = new Components.DayView();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        weekView1 = new Components.WeekView();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        monthView1 = new Components.ProgressGraphCurved();

        jButton1.setText("Day-View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Time Resting: 0 min");

        jLabel2.setText("Time Studying: 0 min");

        jButton2.setText("Week-View");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Month-View");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(92, 92, 92)
                                .addComponent(jButton1)
                                .addGap(29, 29, 29)
                                .addComponent(jButton2)
                                .addGap(44, 44, 44)
                                .addComponent(jButton3))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dayView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(weekView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monthView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(355, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dayView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(weekView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(monthView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(393, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        weekView1.setVisible(false);
        monthView1.setVisible(false);
        dayView1.setVisible(true);
        dayView1.setBounds(100, 120, dayView1.getWidth(), dayView1.getHeight());
            
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        weekView1.setVisible(true);
        monthView1.setVisible(false);
        dayView1.setVisible(false);
        weekView1.setBounds(100, 120, weekView1.getWidth(), weekView1.getHeight());
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        weekView1.setVisible(false);
        monthView1.setVisible(true);
        dayView1.setVisible(false);
        monthView1.setBounds(100, 120, monthView1.getWidth(), monthView1.getHeight());
    }                                        


    // Variables declaration - do not modify                     
    private static Components.DayView dayView1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private static javax.swing.JLabel jLabel1;
    private static javax.swing.JLabel jLabel2;
    private static Components.ProgressGraphCurved monthView1;
    private static Components.WeekView weekView1;
    // End of variables declaration                   
}
