/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panel;

import CleoDevelopmentver1.AddTask;
import Data.MainTasksData;

/**
 *
 * @author peach
 */
public class TasksPanel extends javax.swing.JPanel {
    /**
     * Creates new form FormTask
     */
    public TasksPanel() {
        initComponents();
        taskView1.setTasks(MainTasksData.getMainTasks());
    }

    public void refresh() {
        taskView1.updateTasks();
        revalidate();
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneWin111 = new RavenScrollBar.ScrollPaneWin11();
        taskView1 = new Components.TaskView();
        customColorButton1 = new UIStuff.CustomColorButton();
        deleteDoneTasksButton = new UIStuff.CustomColorButton();

        setMaximumSize(new java.awt.Dimension(1000, 500));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1000, 500));

        scrollPaneWin111.setViewportView(taskView1);

        customColorButton1.setText("Add Task");
        customColorButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customColorButton1ActionPerformed(evt);
            }
        });

        deleteDoneTasksButton.setText("Delete Done Tasks");
        deleteDoneTasksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDoneTasksButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneWin111, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customColorButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteDoneTasksButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(customColorButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 426, Short.MAX_VALUE)
                        .addComponent(deleteDoneTasksButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void customColorButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customColorButton1ActionPerformed
        new AddTask();
    }//GEN-LAST:event_customColorButton1ActionPerformed

    private void deleteDoneTasksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDoneTasksButtonActionPerformed
        // TODO add your handling code here:
        MainTasksData.deleteDoneTasks();
        refresh();
    }//GEN-LAST:event_deleteDoneTasksButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private UIStuff.CustomColorButton customColorButton1;
    private UIStuff.CustomColorButton deleteDoneTasksButton;
    private RavenScrollBar.ScrollPaneWin11 scrollPaneWin111;
    private Components.TaskView taskView1;
    // End of variables declaration//GEN-END:variables
}
