/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panel;
import Model.TimerSpecification;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.Timer;
 
/**
 *
 * @author peach
 */
public class TimerPanel extends javax.swing.JPanel implements ActionListener {
    Timer timer = new Timer(10, this);
    int k = 0;
    int studyDurationInt = 0;
    int restDurationInt = 0;
    boolean isWorking = true;
    boolean extendedWork = false;
    boolean extendedRest = false;
    
    
    JFrame frame2 = new JFrame();
    JLabel label3 = new JLabel("Work Period over!");
    JPanel panel5 = new JPanel();
    JButton button4 = new JButton("5 more minutes");
    JButton button5 = new JButton("Time to rest!");
    
    JFrame frame3 = new JFrame();
    JLabel label4 = new JLabel("Rest is over!");
    JPanel panel6 = new JPanel();
    JButton button6 = new JButton("5 more minutes");
    JButton button7 = new JButton("Ready for Work!");
    
    Model.TimerSpecification defaultPomodoro = new Model.TimerSpecification("Pomodoro Timer", 25,5);
    TimerSpecification[] options = {defaultPomodoro};
    
    

    /**
     * Creates new form FormTimer
     */
    public TimerPanel() {
        initComponents();
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {     
        if (e.getSource() == timer) {
            k++;
            jLabel1.setText(String.valueOf(mins(k) + ":" + secs(k)));
            currentStage.setText(isWorking? "Work Period" : "Rest Period");
        
            
            
            
            if(extendedWork && k == 5 + studyDurationInt) {
                extendedWork = false;
                timer.stop();
                moveToRest();
            }
            else if(extendedRest && k == 5 + restDurationInt) {
                extendedRest = false;
                timer.stop();
                moveToWork();
            }
            
            
            else if(isWorking && k  == studyDurationInt) {
                timer.stop();
                moveToRest();
                //isWorking = false;
                //System.out.println(k);
            }
            
            else if (!isWorking && k == restDurationInt) {
                timer.stop();
                //isWorking = true;
                moveToWork();
                
                
            }
        } if (e.getSource() == button4) { //extend study
            extendedWork = true;
            timer.start();
            frame2.dispose();
            button4.setEnabled(false);
        }
        
        if (e.getSource() == button5) {  
            ProgressPanel.timeStudy = ProgressPanel.timeStudy + k;
            ProgressPanel.updateStudy();
            k = 0;
            timer.start();
            isWorking = false;
            frame2.dispose();
            button4.setEnabled(true);
        }
        if (e.getSource() == button6) { // extend rest
            extendedRest = true;
            timer.start();
            frame3.dispose();
            button6.setEnabled(false);
            
            
        }
        if (e.getSource() == button7) { //move to work
            ProgressPanel.timeRest = ProgressPanel.timeRest + k;
            ProgressPanel.updateRest();
            k = 0;
            timer.start();
            isWorking = true;
            frame3.dispose();
            button6.setEnabled(true);
            
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timerSettings1 = new Components.TimerSettings();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        StudySlider = new javax.swing.JSlider(0, 120, 25);
        RestSlider = new javax.swing.JSlider(0, 120, 5);
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>(options);
        jButton3 = new javax.swing.JButton();
        currentStage = new javax.swing.JLabel();

        setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("00:00");

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Stop");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Set Custom Timer");

        jLabel4.setText("Work Duration");

        jLabel5.setText("Rest Duration");

        StudySlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                StudySliderStateChanged(evt);
            }
        });

        RestSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RestSliderStateChanged(evt);
            }
        });

        jTextField1.setText("25");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("5");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setText("Name of Custom Timer");
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });

        jLabel6.setText("Timer:");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton3.setText("Save Settings");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        currentStage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(131, 131, 131))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(currentStage, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(168, 168, 168)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(StudySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField1)
                                            .addComponent(jTextField2))
                                        .addGap(230, 230, 230))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RestSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(220, 220, 220)))
                        .addComponent(timerSettings1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jButton1)
                        .addGap(44, 44, 44)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(821, 821, 821))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(timerSettings1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(StudySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(currentStage, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(RestSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1)
                                    .addComponent(jButton2))))))
                .addContainerGap(145, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        currentStage.setText(isWorking? "Work Period" : "Rest Period");
        TimerSpecification timerUsed = (TimerSpecification) jComboBox1.getSelectedItem();
        studyDurationInt = timerUsed.studyTime;
        restDurationInt = timerUsed.breakTime;
        timer.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        timer.stop();
        
        if (isWorking) {
            ProgressPanel.timeStudy = ProgressPanel.timeStudy + k;
        } else if (!isWorking) {
            ProgressPanel.timeRest = ProgressPanel.timeRest + k;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void StudySliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_StudySliderStateChanged
        // TODO add your handling code here:
        jTextField1.setText(StudySlider.getValue() + "");
    }//GEN-LAST:event_StudySliderStateChanged

    private void RestSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RestSliderStateChanged
        // TODO add your handling code here:
        jTextField2.setText(RestSlider.getValue() + "");
    }//GEN-LAST:event_RestSliderStateChanged

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        int val1 = Integer.parseInt(jTextField1.getText());
        //StudySlider.setValue(val1);
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        int val2 = Integer.parseInt(jTextField2.getText());
        //RestSlider.setValue(val2);
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained
        // TODO add your handling code here:
        if (jTextField3.getText().equals("Name of Custom Timer")) {
                    jTextField3.setText("");
                }
            
    }//GEN-LAST:event_jTextField3FocusGained

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        // TODO add your handling code here:
        if (jTextField3.getText().equals("")) {
            jTextField3.setText("Name of Custom Timer");
        }
    }//GEN-LAST:event_jTextField3FocusLost

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        Model.TimerSpecification timerChosen =(TimerSpecification) jComboBox1.getSelectedItem();
        StudySlider.setValue(timerChosen.studyTime);
        RestSlider.setValue(timerChosen.breakTime);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        TimerSpecification newCustomTimer = new TimerSpecification(jTextField3.getText(),/* StudySlider.getValue()*/ Integer.parseInt(jTextField1.getText()), Integer.parseInt(jTextField2.getText()));
        TimerSpecification currentlyChosen = (TimerSpecification) jComboBox1.getSelectedItem();
        jComboBox1.addItem(newCustomTimer);
        jTextField3.setText("Name of Custom Timer");
        StudySlider.setValue(currentlyChosen.studyTime);
        RestSlider.setValue(currentlyChosen.breakTime);
        jTextField1.setText(currentlyChosen.studyTime + "");
        jTextField2.setText(currentlyChosen.breakTime + "");
    }//GEN-LAST:event_jButton3ActionPerformed

    
    //helper functions
    private String mins(int k) {
        if ((k / 60) < 10) {
            return "0" + (k / 60);
        } else {
            return k / 60 + "";
        }
    }
    
    private String secs(int k) {
        
        if (k - ((k / 60) * 60) < 10) {
            return "0" + (k - ((k / 60) * 60));
        } else {
            return k - ((k / 60) * 60) + "";
        }
    }
    
    private void moveToRest() {
        
        
        //frame.setTitle("Timer");
        frame2.setSize(300, 120);
        frame2.setLayout(new FlowLayout(3));
        
        button4.addActionListener(this);
        button5.addActionListener(this);
        panel5.add(button4);
        panel5.add(button5);
        frame2.add(label3);
        frame2.add(panel5);
        frame2.setVisible(true);
    }
    
    private void moveToWork() {
        
        frame3.setSize(300, 120);
        frame3.setLayout(new FlowLayout(3));
        
        button6.addActionListener(this);
        button7.addActionListener(this);
        panel6.add(button6);
        panel6.add(button7);
        frame3.add(label4);
        frame3.add(panel6);
        frame3.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider RestSlider;
    private javax.swing.JSlider StudySlider;
    private javax.swing.JLabel currentStage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<Model.TimerSpecification> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private Components.TimerSettings timerSettings1;
    // End of variables declaration//GEN-END:variables
}
