/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UIStuff;

import Model.MainTask;
import Model.Task;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Fishballz
 */
public class ClickableTask extends javax.swing.JPanel {

    /**
     * Creates new form ClickableTask
     */
    int size;
    public ClickableTask(MainTaskItem mainTaskItem) {
        initComponents();
        ArrayList<SubTaskItem> subtaskItems = mainTaskItem.getSubTaskItems();
        
        
        this.size = subtaskItems.size();
        
        setPreferredSize(new java.awt.Dimension(600, 50 * this.size + 70));
        setLayout(new FlowLayout());
        
        add(mainTaskItem);
        
        JPanel subTaskPanels = new JPanel();
        for (int i = 0; i < this.size; i++) {
            subTaskPanels.add(subtaskItems.get(i));
        }
        subTaskPanels.setPreferredSize(new Dimension(550, 50 * this.size));
        
        subTaskPanels.setLayout(new FlowLayout());
        subTaskPanels.setOpaque(false);
        subTaskPanels.setVisible(true);
        add(subTaskPanels);
        
        
        jLabel1.setIcon(new ImageIcon("src/main/java/TempIcons/downArrow.png"));
        jLabel1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                toggleVisibility(subTaskPanels);
            }
        });
 
    }
    
    public ClickableTask() {
        initComponents();
        
        MainTask mainTask = new MainTask("test", "23/12/2012", 3);
        mainTask.subTasks.add(new Task("test", "20/12/2012", 3));
        mainTask.subTasks.add(new Task("iamapotatowagon", "21/12/2012", 3));
        mainTask.subTasks.add(new Task("test3", "22/12/2012", 3));
        
        setPreferredSize(new java.awt.Dimension(550, 30));
        
        setLayout(new FlowLayout());
        
        MainTaskItem mainTaskItem = new MainTaskItem(mainTask);
        add(mainTaskItem);
        
        JPanel subTaskPanels = new JPanel();
        for (int i = 0; i < mainTask.subTasks.size(); i++) {
            subTaskPanels.add(new SubTaskItem(mainTaskItem, mainTask.subTasks.get(i)));
        }
        subTaskPanels.setPreferredSize(new Dimension(550, 50 * mainTask.subTasks.size()));
        
        subTaskPanels.setLayout(new FlowLayout());
        subTaskPanels.setOpaque(false);
        subTaskPanels.setVisible(true);
        add(subTaskPanels);
        
        
        jLabel1.setIcon(new ImageIcon("src/main/java/TempIcons/downArrow.png"));
        jLabel1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                toggleVisibility(subTaskPanels);
            }
        });
        
        
    }
    
    public void toggleVisibility(JPanel panel) {
        if (panel.isVisible()) {
            jLabel1.setIcon(new ImageIcon("src/main/java/TempIcons/upArrow.png"));
            setPreferredSize(new java.awt.Dimension(600, 55));
        } else{
            jLabel1.setIcon(new ImageIcon("src/main/java/TempIcons/downArrow.png"));
            setPreferredSize(new java.awt.Dimension(600, 50 * size + 100));
        }
        
        
        panel.setVisible(!panel.isVisible());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 517, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 300, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
