/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UIStuff;

import Model.MainTask;
import Model.SubTask;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JProgressBar;

/**
 *
 * @author peach
 */
public class MainTaskItem extends javax.swing.JPanel {
    
    final private MainTask mainTask;
    
    private ArrayList<SubTaskItem> subTaskItems;
    private int subTasksSize;
    
    final private JProgressBar bar = new JProgressBar() {
            @Override
            protected void paintBorder(Graphics g) {
                // Override to remove border painting
            }
        };
    
     /**
     * Creates new form MainTaskItem
     */
    public MainTaskItem(MainTask mainTask) {
        initComponents();
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        dueDate.setText(df.format(mainTask.deadline));
        priority.setText(String.valueOf(mainTask.priority));
        task.setText(mainTask.task);
        
        this.mainTask = mainTask;
        this.subTaskItems = new ArrayList();
        this.subTasksSize = mainTask.numOfSubTasks();
        
        for (int i = 0; i< subTasksSize; i++) {
            subTaskItems.add(new SubTaskItem(this, i));
        }
        
        setOpaque(false);
        
        bar.setBounds(10,40,500,2);
        
        updateProgressBar();
        add(bar); 
    }
   
    
    public ArrayList<SubTaskItem> getSubTaskItems() {
        return subTaskItems;
    }
    
        
    /**
     * Get the subTask object of the mainTask object
     * @param index index of subTask in the mainTask object
     * @return The queried subTask
     */
    
    public SubTask getSubTask(int index) {
        return mainTask.getSubTask(index);
    }

     
    final public void updateProgressBar() {
        int completedWeight = 0;
        int totalWeight = 0;
        for (int i = 0; i < subTasksSize ;i++) {
            int weight = subTaskItems.get(i).getWeight();
            boolean done = subTaskItems.get(i).getDone();
            totalWeight += weight;
            if (done) {
                completedWeight += weight;
            }
        }

        if (totalWeight == completedWeight)
        {
            task.setSelected(true);
            toggleDone(true);
        }
        
        else {
            task.setSelected(false);
            toggleDone(false);
        }
             
        if (totalWeight != 0) {
            bar.setValue((completedWeight*100)/(totalWeight));
        } else {
            bar.setValue(100);
        }
        
    }
    
    
    
    private void toggleDone(boolean bool) {
        mainTask.done = bool;
        showDone(bool);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dueDate = new javax.swing.JLabel();
        priority = new javax.swing.JLabel();
        task = new javax.swing.JCheckBox();

        dueDate.setText("deadline");

        priority.setText("priority");

        task.setText(" Task");
        task.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(task, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addGap(64, 64, 64)
                .addComponent(dueDate)
                .addGap(18, 18, 18)
                .addComponent(priority)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(task)
                    .addComponent(dueDate)
                    .addComponent(priority))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void taskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskActionPerformed
        // TODO add your handling code here:
        toggleDone(task.isSelected());
                
        if (task.isSelected()){
            for (int i = 0; i < subTasksSize; i++) {
                subTaskItems.get(i).toggleDone(true);
            }
        } else {
            for (int i = 0; i < subTasksSize; i++) {
                subTaskItems.get(i).toggleDone(false);
            } 
        }
        
        updateProgressBar();
    }//GEN-LAST:event_taskActionPerformed

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D)g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        
        g2.setColor(new Color(235,255,250));
        g2.fillRoundRect(0,0, getWidth(), getHeight(), 10,10);
        
        super.paintComponent(g);
    }
    
       /**
     * Show visually if the task is completed or not on the UI.
     */
    private void showDone(boolean bool) {
        if (bool == true){
            task.setForeground(Color.GRAY);
            priority.setForeground(Color.GRAY);
            dueDate.setForeground(Color.GRAY);
        } else {
            task.setForeground(Color.BLACK);
            priority.setForeground(Color.BLACK);
            dueDate.setForeground(Color.BLACK);
        }
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dueDate;
    private javax.swing.JLabel priority;
    private javax.swing.JCheckBox task;
    // End of variables declaration//GEN-END:variables
}
