/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UIStuff;

import Model.MainTask;
import Model.Task;
import com.google.common.primitives.Ints;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.ArrayList;
import javax.swing.JProgressBar;

/**
 *
 * @author peach
 */
public class MainTaskItem extends javax.swing.JPanel {
    
    
    /**
     * Creates new form MainTaskItem
     */
    
    private MainTask mainTask;
    private JProgressBar bar = new JProgressBar() {
            @Override
            protected void paintBorder(Graphics g) {
                // Override to remove border painting
            }
        };
    private ArrayList<SubTaskItem> subTaskItems;
    private ArrayList<Task> subTasks;
    private int subTasksSize;
    private boolean subTasksDoneHistory[];
    
    
    public MainTaskItem(MainTask mainTask) {
        initComponents();
        dueDate.setText(mainTask.deadline);
        priority.setText(String.valueOf(mainTask.priority));
        task.setText(mainTask.task);
        this.mainTask = mainTask;
        this.subTaskItems = new ArrayList();
        this.subTasks = mainTask.subTasks;
        this.subTasksSize = mainTask.subTasks.size();
        this.subTasksDoneHistory = new boolean[subTasksSize];
        
        setOpaque(false);
        
        bar.setBounds(10,40,500,2);
        
        updateProgressBar();
        add(bar);
        
        for (int i = 0; i< subTasksSize; i++) {
            Task subtask = subTasks.get(i);
            subTaskItems.add(new SubTaskItem(this, subtask));
        }
        
        
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D)g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        
        g2.setColor(new Color(235,255,250));
        g2.fillRoundRect(0,0, getWidth(), getHeight(), 10,10);
        
        super.paintComponent(g);
    }
    
    public ArrayList<SubTaskItem> getSubTaskItems() {
        return subTaskItems;
    }
    
    public void updateProgressBar() {
        int completedWeight = 0;
        int totalWeight = 0;
        int completed = 0;
        for (int i = 0; i < subTasksSize ;i++) {
            Task subTask = subTasks.get(i);
            totalWeight += subTask.weight;
            if (subTask.done) {
                completedWeight += subTask.weight;
                completed++;
            }
        }

        if (completed == mainTask.subTasks.size())
        {
            task.setSelected(true);
            toggleDone(true);
        }
        
        else {
            task.setSelected(false);
            toggleDone(false);
        }
             
        
        bar.setValue((completedWeight*100)/(totalWeight));
        
 
        //System.out.println((completedWeight*100)/totalWeight);
    }
    
    private void toggleDone(boolean bool) {
        mainTask.done = bool;
        
        if (bool == true){
            task.setForeground(Color.GRAY);
            priority.setForeground(Color.GRAY);
            dueDate.setForeground(Color.GRAY);
        } else {
            task.setForeground(Color.BLACK);
            priority.setForeground(Color.BLACK);
            dueDate.setForeground(Color.BLACK);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dueDate = new javax.swing.JLabel();
        priority = new javax.swing.JLabel();
        task = new javax.swing.JCheckBox();

        dueDate.setText("deadline");

        priority.setText("priority");

        task.setText(" Task");
        task.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(task, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addGap(64, 64, 64)
                .addComponent(dueDate)
                .addGap(18, 18, 18)
                .addComponent(priority)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(task)
                    .addComponent(dueDate)
                    .addComponent(priority))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void taskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskActionPerformed
        // TODO add your handling code here:
        toggleDone(task.isSelected());
        
        if (task.isSelected()){
            for (int i = 0; i < subTasksSize; i++) {
                subTasksDoneHistory[i] = subTasks.get(i).done;
                subTasks.get(i).done = true; 
                subTaskItems.get(i).toggleDone(true);
            }
            bar.setValue(100);
        } else {
            for (int i = 0; i < subTasksSize; i++) {
                subTaskItems.get(i).toggleDone(subTasksDoneHistory[i]);
            }
            updateProgressBar();
        }
    }//GEN-LAST:event_taskActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dueDate;
    private javax.swing.JLabel priority;
    private javax.swing.JCheckBox task;
    // End of variables declaration//GEN-END:variables
}
