/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UIStuff;

import Model.SubTask;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author peach
 */
public class SubTaskItem extends javax.swing.JPanel {

    final private SubTask subTaskObject;
    final private MainTaskItem mainTaskItem;
    boolean prevDone;
    
    /**
     * Creates new form SubTaskItem.
     * @param mainTaskItem 
     * @param index index of the subTask array of the mainTask object.
     */
    protected SubTaskItem(MainTaskItem mainTaskItem, int index) {
        initComponents();
        this.mainTaskItem = mainTaskItem;
        this.subTaskObject = mainTaskItem.getSubTask(index);
        this.prevDone = false;
        
        dueDate.setText(subTaskObject.deadline);
        subtask.setText(subTaskObject.task);
        this.setOpaque(false);
    }

    /**
     * Sets the subTask object and item to be (not) done, also saves Boolean state before change. 
     * @param bool set true if task is done, and false otherwise.
     */
    protected void toggleDone(boolean bool) {
 
        //TODO: simplify this code somehow
        
        if (bool){
            prevDone = subTaskObject.done;
            subTaskObject.done = true;
            showDone(true);
            subtask.setSelected(true);
        } else if (prevDone){
            subTaskObject.done = true;
            showDone(true);
            subtask.setSelected(true);
        } else {
            showDone(false);
            subTaskObject.done = false;
            subtask.setSelected(false);
        }
    } 
    
    protected boolean getDone() {
        return subTaskObject.done;
    }
    
    protected int getWeight() {
        return subTaskObject.weight;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dueDate = new javax.swing.JLabel();
        subtask = new javax.swing.JCheckBox();

        dueDate.setText("dueDate");

        subtask.setText("jCheckBox1");
        subtask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(subtask, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addGap(65, 65, 65)
                .addComponent(dueDate)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dueDate)
                    .addComponent(subtask))
                .addGap(8, 8, 8))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void subtaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtaskActionPerformed
        // TODO add your handling code here:
        
        if (subtask.isSelected()) {
            showDone(true);
            subTaskObject.done = true;
        } else {
            showDone(false);
            subTaskObject.done = false;
        }
        
        mainTaskItem.updateProgressBar();
    }//GEN-LAST:event_subtaskActionPerformed

    /**
     * Show visually if the task is completed or not on the UI.
     */
    private void showDone(boolean bool) {
        if (bool) {
            subtask.setForeground(Color.GRAY);
            dueDate.setForeground(Color.GRAY);
        } else {
            subtask.setForeground(Color.BLACK);
            dueDate.setForeground(Color.BLACK);
        }
    }
    
    /**
     * Designing how the SubTaskItem should look like. 
     */
    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D)g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(new Color(250,255,255));
        g2.fillRoundRect(0,0, getWidth(), getHeight(), 10,10);
        
        super.paintComponent(g);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dueDate;
    private javax.swing.JCheckBox subtask;
    // End of variables declaration//GEN-END:variables
}
